#!/bin/bash

# API Keys
export VAULT_TOKEN=<VAULT_TOKEN>
export ES_PASSWORD=<ES_PASSWORD>
export KEYCLOAK_ADMIN_PASSWORD=<KEYCLOAK_ADMIN_PASSWORD>
export AWS_ACCESS_KEY=<AWS_ACCESS_KEY>
export AWS_SECRET_KEY=<AWS_SECRET_KEY>

# Client Keys
export REACT_APP_GOOGLE_MAPS_API_KEY=<REACT_APP_GOOGLE_MAPS_API_KEY>
export REACT_APP_BOX_CLIENT_ID=<REACT_APP_BOX_CLIENT_ID>
export REACT_APP_DROPBOX_APP_KEY=<REACT_APP_DROPBOX_APP_KEY>
export REACT_APP_GOOGLE_DRIVE_CLIENT_ID=<REACT_APP_GOOGLE_DRIVE_CLIENT_ID>
export REACT_APP_GOOGLE_DRIVE_DEVELOPER_KEY=<REACT_APP_GOOGLE_DRIVE_DEVELOPER_KEY>
export REACT_APP_ONEDRIVE_CLIENT_ID=<REACT_APP_ONEDRIVE_CLIENT_ID>

curl -X POST \
  http://localhost:8200/v1/kv/atlas-api-keys \
  -H 'Content-Type: application/json' \
  -H 'X-Vault-Token: '"$VAULT_TOKEN"'' \
  -d '{
  "ES_PASSWORD": "'"$ES_PASSWORD"'"",
  "KEYCLOAK_ADMIN_PASSWORD": "'"$KEYCLOAK_ADMIN_PASSWORD"'"",
  "AWS_ACCESS_KEY": "'"$AWS_ACCESS_KEY"'"",
  "AWS_SECRET_KEY": "'"$AWS_SECRET_KEY"'""
}'

curl -X POST \
  http://localhost:8200/v1/kv/atlas-keys \
  -H 'Content-Type: application/json' \
  -H 'X-Vault-Token: '"$VAULT_TOKEN"'' \
  -d '{
  "REACT_APP_GOOGLE_MAPS_API_KEY": "'"$REACT_APP_GOOGLE_MAPS_API_KEY"'"",
  "REACT_APP_BOX_CLIENT_ID": "'"$REACT_APP_BOX_CLIENT_ID"'"",
  "REACT_APP_DROPBOX_APP_KEY": "'"$REACT_APP_DROPBOX_APP_KEY"'"",
  "REACT_APP_GOOGLE_DRIVE_CLIENT_ID": "'"$REACT_APP_GOOGLE_DRIVE_CLIENT_ID"'"",
  "REACT_APP_GOOGLE_DRIVE_DEVELOPER_KEY": "'"$REACT_APP_GOOGLE_DRIVE_DEVELOPER_KEY"'"",
  "REACT_APP_ONEDRIVE_CLIENT_ID": "'"$REACT_APP_ONEDRIVE_CLIENT_ID"'""
}'